
resources:
  repositories:
    - repository: templates
      type: git
      name: Area-Engenharia/templates
      ref: refs/heads/develop/2.0.0
#  #   
stages:
- template: BuildTemplates/azure-pipelines.yaml@templates
  parameters:
      namespace: 'poc'
      app: 'sample'
      coveragetest: false
      variables: 'teste'