
resources:
  repositories:
    - repository: templates
      type: git
      name: Area-Engenharia/templates
      ref: refs/heads/release
      
stages:
- template: BuildTemplates/azure-pipelines.yaml@templates
  parameters:
      namespace: 'b2c'
      app: 'cupons'
      coveragetest: false